---
- name: Install software
  hosts: windows_workstation
  tasks:
  - name: install 7zip
    win_chocolatey:
      name: 7zip
      state: present

  - name: Install git
    win_chocolatey:
      name: git
      state: present

  - name: Install vscode
    win_chocolatey:
      name: vscode
      state: present

  - name: Install chrome
    win_chocolatey:
      name: googlechrome
      state: present

  - name: Install putty
    win_chocolatey:
      name: putty
      state: present

  - name: Install python3
    win_chocolatey:
      name: python3
      state: present

  - name: Install sharex
    win_chocolatey:
      name: sharex
      state: present