---
- name: Domain Join
  hosts: domain_join
  vars_prompt:
   - name: admin_user
      prompt: Admin User
      private: no
    - name: admin_password
      prompt: Admin Password
      private: yes
  tasks:
  - name: set dns to blue_dns
    ansible.windows.win_dns_client
      adapter_names: Ethernet
      dns_servers: 10.0.5.10

  - name: Join to Domain
    ansible.windows.win_domain_membership:
      dns_domain_name: blue2.local
      hostname: vanhalen
      domain_admin_user: {{ admin_user }}
      domain_admin_password: {{ admin_password }}
      domain_ou_path: "OU=servers,OU=Computers,OU=blue2,DC=blue2,DC=local"
      state: domain
    register: domain_state

  - name: reboot in needed
    ansible.windows.win_reboot:
      when: domain_state.reboot_required
