---
- name: Domain Join
  hosts: windows_workstation
  gather_facts: true
  vars_prompt:
  - name: admin_user
    prompt: Admin User
    private: no
  - name: admin_password
    prompt: Admin Password
    private: yes
  tasks:
  - name: set dns to blue_dns
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 10.0.5.10

  - name: Join to Domain
    win_domain_membership:
      dns_domain_name: blue2.local
      hostname: "{{ ansible_hostname }}"
      domain_admin_user: "{{ admin_user }}"
      domain_admin_password: "{{ admin_password }}"
      domain_ou_path: "OU=Workstations,OU=Computers,OU=blue2,DC=blue2,DC=local"
      state: domain
    register: domain_state

  - name: reboot in needed
    win_reboot:
    
