---
- name: parse a csv file and loop tasks.
  hosts: domain_controller
  tasks:  
  - name: read group_csv
    read_csv:
      path: /home/ben/SYS-480-01-SEC-480-01-NET-480-01/ansible/windows/groups.csv
    register : items
    delegate_to: localhost

  - name: loop group creation
    win_domain_group:
      name: "{{ item.group }}"
      category: security
      orignizational_unit: OU=Groups,OU=Accounts,OU=blue2,DC=blue2,DC=local
      scope: domainlocal
    with_items: "{{ items.list }}"