---
- name: Create OUs
  hosts: windows
  gather_facts: no

  tasks:
  - name: create a deploy directory
    win_file:
      path: C:\480
      state: directory

  - name: load from jinja
    win_template:
      src: /home/ben/SYS-480-01-SEC-480-01-NET-480-01/ansible/windows/rdp.ps1.j2
      dest: C:\480\rdp.ps1
  - name: run script
    async: 10
    poll: 0
    win_shell:
      C:\480\rdp.ps1