---
- name: windows-networking
  hosts: domain_join
  gather_facts: no
  vars_prompt:
  - name: adminpassword
    prompt: "New admin pass"
    private: yes

  tasks:
  - name: set local admin
    win_user:
      name: Administrator
      password: "{{ adminpassword }}"
      state: present
      password_never_expires: yes

  - name: Change time zone
    win_timezone:
        timezone: Eastern Standard Time
    register: timezone

  - name: set the hostname
    win_hostname:
      name: "vanhalen"
  
  - name: create a deploy directory
    win_file:
      path: C:\480
      state: directory
  - name: load from jinja
    win_template:
      src: /home/ben/SYS-480-01-SEC-480-01-NET-480-01/ansible/windows/static.ps1.j2
      dest: C:\480\static.ps1
  - name: run script
    async: 10
    poll: 0
    win_shell:
      C:\480\static.ps1
    